### ISSUE TITLE
False Positive: unittest.TestCase.setUp

### ISSUE THREAD

**Issue by toddrjen** [flintwork/pep8-naming#14]
When making unit tests using the built-in `unittest` module, python defines a `setUp` method for `unittest.TestCase` that is used to do standard setup operations for all tests.  Users have to override this method, and thus use this name, to do the setup, but pep8-naming nevertheless flags it as violating `N802 function name should be lowercase`.  Since it is something in the standard library that users have no control over, it shouldn't violate the rule.

**Comment by lensvol** [comment]
Is there any progress on this issue? I would like to try and fix it, really gets on my nerves. :)

**Comment by sigmavirus24** [comment]
This is a duplicate of #6.
