### ISSUE TITLE
Allow camelCase for python standard libraries.

### ISSUE THREAD

**Issue by remcohaszing** [flintwork/pep8-naming#6]
(Unfortunately) some libraries in the python standard library do not follow pep8. This means that people using them are forced to write non pep8-compliant code. This code should be accepted by the pep8-naming plugin.
For example unittest.TestCase is meant to be overridden so setUp and tearDown can be implemented. The same goes for logging.Logger.

**Comment by sigmavirus24** [comment]
@lensvol feel free to try to fix this.

**Comment by staeff** [comment]
+1

**Comment by sigmavirus24** [comment]
@staeff care to submit a fix?

**Comment by staeff** [comment]
I'll look into it, but can't promise anything. I just came across this issue, when I was researching the problem.

**Comment by sigmavirus24** [comment]
@staeff then please understand that adding a +1 to a known issue that the maintainers are willing to accept a patch for is patently unhelpful.

**Comment by staeff** [comment]
@sigmavirus24 oops, sorry.

**Comment by sigmavirus24** [comment]
No worries.
